[package]
name = "mergezip_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
zip = "0.6"
glob = "0.3"
time = { version = "0.3", features = ["formatting"] }
